import type { Metadata } from "next";
import { Chivo, Rasa } from "next/font/google";
import "./globals.css";
import Header from "@components/layout/Header";

const chivo = Chivo({
  variable: "--font-chivo",
  subsets: ["latin"],
});

const rasa = Rasa({
  variable: "--font-rasa",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chivo.variable} ${rasa.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
